language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t marcelotozzi/docker-react -f Dockerfile.dev .

script:marcelotozzi
  - docker run -e CI=true marcelotozzi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-229268933693"
  bucket_path: "docker-react"